services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - postgres/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      bookmark-network:
        aliases:
          - user-db
          - bookmark-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - bookmark-network
    volumes:
      - redis_data:/data
    restart: unless-stopped

  user-service:
    image: huypham053/user-service:${USER_SERVICE_TAG:-latest}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - user-service/.env
    networks:
      - bookmark-network
    volumes:
      - ./keys:/app/keys:ro
    restart: unless-stopped

  bookmark-service:
    image: huypham053/bookmark-service:${BOOKMARK_SERVICE_TAG:-latest}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - bookmark-service/.env
    networks:
      - bookmark-network
    volumes:
      - ./keys/public.pem:/app/keys/public.pem:ro
    restart: unless-stopped

  bookmark-portal:
    image: ebvn/bookmark-app-portal:ddd
    depends_on:
      - user-service
      - bookmark-service
    networks:
      - bookmark-network
    restart: unless-stopped

  bookmark-nginx:
    image: nginx:alpine
    depends_on:
      - user-service
      - bookmark-service
      - bookmark-portal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bookmark-network
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file:
      - ./config/cloudflared.env
    command: tunnel --no-autoupdate --protocol http2 run
    networks:
      - bookmark-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  bookmark-network:
    driver: bridge